### ISSUE TITLE
Implement entreprise submission form with discord integration

### ISSUE THREAD

**Issue by eljily** [abdelhalimjean/entreprises#11]
1.	Create the Form Component:
	•	Generate a new component named AddEnterpriseComponent using Angular CLI.
	•	The form should collect the following enterprise details:
	•	Name
	•	Logo URL
	•	Short Description
	•	Long Description
	•	Sectors (multiple selection)
	•	Technologies Used (multiple selection)
	•	Address Information:
	•	Location
	•	Phone Number
	•	Website
	•	Social Media Links (LinkedIn, Facebook, Instagram, WhatsApp, YouTube, Twitter, GitHub, GitLab, Telegram, Discord)

note : maybe other fields are needed check for it.

	2.	Build the Form Template:
	•	In add-enterprise.component.html, create input fields for each of the required details.
	•	Ensure appropriate form validation to check for required fields and correct data formats (e.g., URLs).
	3.	Handle Form Submission:
	•	In add-enterprise.component.ts, define the enterprise object and handle the form submission logic.
	•	Use HttpClient to send the form data to the specified Discord webhook URL in JSON format.
	4.	Integrate with Discord Webhook:
	•	Obtain a Discord webhook URL from your Discord server settings and store it securely.
	•	In the form submission logic, POST the JSON object containing the enterprise details to the Discord webhook using HttpClient.

The primary objective of this issue is to enable users to submit new enterprise information through a form. Upon submission, the data will be automatically forwarded to one of our Discord channels. Subsequently, a member of our community will review the submitted information and initiate a pull request (PR) to incorporate the details into our repository after thorough examination.

**Comment by abdelhalimjean** [comment]
i suggest splitting this feature and working on it in steps:

1. creating the form (with validation)
2. submitting the form to the json server ( as marked in #3 )
3. and once that's stable we can submit the data to discord webhooks

**Comment by eljily** [comment]
@abdelhalimjean I dont think we need this anymore.

**Comment by abdelhalimjean** [comment]
using google forms makes this redundant for now
